# Generated by Django 3.2.18 on 2023-04-30 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="event_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
