# Generated by Django 3.2.18 on 2023-04-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="tickets_per_session",
            field=models.SmallIntegerField(
                choices=[("20", "20"), ("25", "25"), ("30", "30")], default="20"
            ),
        ),
    ]
