# Generated by Django 3.2.18 on 2023-05-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20230504_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='tickets_per_session',
            new_name='max_capacity',
        ),
    ]
