# Generated by Django 3.2.18 on 2023-05-10 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0011_alter_event_tour_times"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="likes",
        ),
    ]
