# Generated by Django 3.2.18 on 2023-05-02 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_auto_20230501_2042"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="last_name",
        ),
    ]
