# Generated by Django 3.2.18 on 2023-05-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0005_alter_contact_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
