# Generated by Django 3.2.18 on 2023-05-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_carouselimage_cta_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="carouselimage",
            name="cta_url",
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
