# Generated by Django 3.2.18 on 2023-05-04 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0007_alter_booking_booking_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["user", "title"]},
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="ticket_number",
            new_name="num_tickets",
        ),
    ]
