# Generated by Django 3.2.18 on 2023-05-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0008_auto_20230504_1801"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="num_tickets",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
