# Generated by Django 3.2.18 on 2023-05-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0009_alter_booking_num_tickets"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["title"]},
        ),
        migrations.AlterField(
            model_name="booking",
            name="num_tickets",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                default="2",
                max_length=50,
            ),
        ),
    ]
